"""
SQLAlchemy ORM base class and composable mixins.

Every domain model inherits from Base plus the appropriate mixins.
The mixin composition keeps models DRY while remaining explicit:

    class School(TenantMixin, SoftDeleteMixin, TimestampMixin, UUIDMixin, Base):
        __tablename__ = "schools"
        ...
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedColumn, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base. All ORM models inherit from this."""

    type_annotation_map: dict[type, Any] = {
        datetime: DateTime(timezone=True),
        uuid.UUID: UUID(as_uuid=True),
    }


# ── Mixins ────────────────────────────────────────────────────────────────────

class UUIDMixin:
    """UUID primary key, generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Automatic created_at / updated_at timestamps (UTC)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """
    Soft-delete support via deleted_at timestamp.

    Repositories must filter WHERE deleted_at IS NULL in all normal queries.
    Hard deletes are prohibited at the application layer.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class TenantMixin:
    """
    trust_id foreign key present on every tenant-scoped table.
    RLS policies enforce that rows are only visible within the correct trust.
    """

    trust_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("trusts.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
